name: Release Marijan Tunnel Manager

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: ["386", "amd64", "arm64"]
        exclude:
          # windows/386 and darwin/386 seems useless
          - goarch: "386"
            goos: windows
          - goarch: "386"
            goos: darwin
    steps:
      - name: Get Release Info
        run: |
          echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "OS_NAME=${{ matrix.goos }}" >> $GITHUB_ENV
      - name: OS darwin
        if: matrix.goos == 'darwin'
        run: echo "OS_NAME=macOS" >> $GITHUB_ENV
      - uses: actions/checkout@v5
      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: 1.24.9
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: marijan
          ldflags: -X "main.currentVersion=${{ env.RELEASE_TAG }}"